name: basic checks

on:
  push:
  pull_request:

jobs:
  basic-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install test dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive

          sudo apt-get update
          sudo apt-get install --no-install-recommends -y \
            pandoc \
            weasyprint

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pymarkdownlnt pytest

      - name: Run tests
        run: pytest -v starter_tests

      - name: Upload generated PDF
        uses: actions/upload-artifact@v4
        with:
          name: README.pdf
          path: README.pdf
