name: Convert Markdown to PDF

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-pdfs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pandoc and LaTeX
        run: |
          sudo apt update
          sudo apt install -y pandoc texlive-xetex

      - name: Convert all Markdown files to PDF
        run: |
          mkdir -p pdf_output
          for file in $(find . -name "*.md"); do
            filename=$(basename "$file" .md)
            pandoc "$file" -o "pdf_output/${filename}.pdf" --standalone --pdf-engine=xelatex
          done

      - name: Upload PDFs as build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: generated-pdfs
          path: pdf_output/
